### ISSUE TITLE
FS Upload/Download Utility

### ISSUE THREAD

**Issue by aldmbmtl** [aldmbmtl/hfx-pipeline#1]
We need to make a general use upload/download utility in python that is attached to a Lambda function and bound to the FS API Gateway in AWS. 

Requirements
- Take the credentials from the project the user is making the request to know which bucket to upload to.
- This needs to support uploading and downloading from the PROJECTS bucket. The AWS Access and Secret Keys as well as target bucket are stored on the Projects data object.
- Upload any kind of file type (This is an API Gateway thing I have messed with but have not done yet fully)

**Comment by mccullen00** [comment]
Dope, I’ll get started this evening.

**Comment by aldmbmtl** [comment]
I wrote a section on the layout of data transportation and authentication in the HFX Documentation [here](https://aldmbmtl.github.io/hfx-pipeline/fs_model.html#cloud-storage). The graph shows the correct flow through the authentication system as well. 

The REST API calls should look as follows:

1. Uploading: https://api.hatfieldfx.com/fs/{Project ID}/{Object ID}/upload?key=s3FilePath GET 
2. Download: https://api.hatfieldfx.com/fs/{Project ID}/{Object ID}/download?key=s3FilePath GET 

These should both return generated signed urls that expire in 15 mins to the s3 bucket key requested. Signed URLs passed by S3 can be used to upload and download. S3 will upload to the clients bucket for us.

**Comment by aldmbmtl** [comment]
Utility built, tested and functional.
